### ISSUE TITLE
JSON logs appear in Sumo as strings

### ISSUE THREAD

**Issue by lacer93** [SumoLogic/sumologic-lambda-extensions#13]
## Description

When using the sumologic-lambda-extension to send lambda logs to SumoLogic originally JSON logs appear as strings in Sumo.

Log in CloudWatch:
![image](https://user-images.githubusercontent.com/11597193/157486202-ce63de25-aadc-45c6-8983-a8dcde6ef017.png)
Log in SumoLogic:
![image](https://user-images.githubusercontent.com/11597193/157486262-0d8db977-81ab-4903-bb89-161147e2a1da.png)

## Steps to Reproduce
Use a JSON formatter to emit logs in JSON format I guess?

## Expected Behavior
I'd expect the logs in Sumo to be properly parsed as JSON logs so that they can be expanded/collapsed/queried etc.

## Relevant Logs / Console output

[NOTE]: # ( Please provide error logs if possible. )

## Your Environment

```
          SUMO_LOG_LEVEL: error
          SUMO_LOG_TYPES: function
```

## Additional context

Also as a related sidenote/feature request: could we have an envvar switch to have the logs delivered to sumo without any additional information wrapping the actual log message? So no `IsColdStart`, `LayerVersion` etc. only the log message itself sent to Sumo?

**Comment by surfous** [comment]
I'd like to +1 this issue. We're trying to migrate from using the reflector Lambda for CloudWatch Logs to the extension, but and JSON we log using the extension gets formatted as a string. 

The reflector Lambda explicitly checks whether a log message is JSON and handles it accordingly: https://github.com/SumoLogic/sumologic-aws-lambda/blob/90f280daf89d13d7f672101c5b3eec7081713a8b/cloudwatchlogs/cloudwatchlogs_lambda.js#L197-L203

**Comment by rb62680** [comment]
@himanshu219 The pull request for this issue was merged but no new version of the layer was created (if I'm not mistaken, we're still at version 3 which points to release v1.0.2). Is a new release coming soon?

**Comment by himanshu219** [comment]
Created the new  release https://github.com/SumoLogic/sumologic-lambda-extensions/releases/tag/v1.0.3

**Comment by jose-garrido-martinez** [comment]
I have tried https://github.com/SumoLogic/sumologic-lambda-extensions/releases/tag/v1.0.3. and the message is still being shown as string instead of a JSON. 
Did it work for you @surfous ?

**Comment by surfous** [comment]
@jose-garrido-martinez Yes, however there is a catch. You must ensure the entire log message is valid JSON, with no extra string data surrounding it. 

For example, the golang logger (my Lambdas were written in golang) by default prepended a timestamp to each log message. This would cause log data to be cast as a string rather than JSON, even with this change in place. I had to change the default config of the logger to not add anything to my log messages.

I'd suggest checking for this kind of thing that may be modifying what you're logging out before it gets to the Lambda extension.

**Comment by jose-garrido-martinez** [comment]
yep!!! That is what is happening!! :/ :/ 
![image](https://user-images.githubusercontent.com/115574429/195147613-78042ea4-7d86-4b85-9ad1-444614c17c63.png)

We'll investigate that. 
Thanks a lot

**Comment by jose-garrido-martinez** [comment]
Hello @surfous sorry for bothering you, but, checking the source code of the extension. Is not this code intended to be removing that part and being able to send to sumo without that extra information?
```
// Regex used to detect logs coming from lambda functions.
// The regex will parse out the requestID and strip the timestamp
// Example: 2016-11-10T23:11:54.523Z    108af3bb-a79b-11e6-8bd7-91c363cc05d9    some message
var consoleFormatRegex = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z\s(\w+?-\w+?-\w+?-\w+?-\w+)\s(INFO|ERROR|WARN|DEBUG)?/;
......
 // Attempt to detect console log and auto extract requestID and message
  var consoleLog = consoleFormatRegex.exec(log.message);
  if (consoleLog !== null) {
      lastRequestID = consoleLog[1];
      log.message = log.message.substring(consoleLog[0].length);
  }

  // Auto detect if message is json
  try {
      log.message = JSON.parse(log.message);
  } catch (err) {
      // Do nothing, leave as text
      log.message = log.message.trim();
  }
```

**Comment by jose-garrido-martinez** [comment]
Actually I have tested the code of this (standalone in a script) https://github.com/SumoLogic/sumologic-aws-lambda/blob/main/cloudwatchlogs/cloudwatchlogs_lambda.js and the result is removing the undesirable information. Not sure why it is not working used in the extension

**Comment by surfous** [comment]
I'm not familiar with altering nodejs logging format in Lambda. Maybe this will get you closer to what you need? https://stackoverflow.com/questions/42843905/change-log-format-of-cloudwatch-logs-from-lambda-node-js
