### ISSUE TITLE
The same layer version is specified for v1.0.2 and v1.0.3 in github releases

### ISSUE THREAD

**Issue by ykitamura-mdsol** [SumoLogic/sumologic-lambda-extensions#16]
## Description

The layer version is not updated in the v1.0.3 release note. I assume the latest version is `4`:

https://github.com/SumoLogic/sumologic-lambda-extensions/releases/tag/v1.0.3
<img width="942" alt="Screen Shot 2022-07-29 at 10 17 37 AM" src="https://user-images.githubusercontent.com/16286071/181779926-2e61dc1d-dfbc-46db-b535-f43d64d9a074.png">

https://github.com/SumoLogic/sumologic-lambda-extensions/releases/tag/v1.0.2
<img width="930" alt="Screen Shot 2022-07-29 at 10 17 45 AM" src="https://user-images.githubusercontent.com/16286071/181779893-2eadd38f-56f5-44f7-a00c-d7fb689820d0.png">

**Comment by himanshu219** [comment]
Yes version is 4
