### ISSUE TITLE
Req: Add KMS encrypted endpoint option [PR Included]

### ISSUE THREAD

**Issue by nhenjes** [SumoLogic/sumologic-lambda-extensions#21]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Since the endpoint URL includes an authentication key, I would like to be able to supply a KMS encrypted value in the SUMO_HTTP_ENDPOINT env var and have the lambda decrypt the var once running. There could also be a variable cache timeout option to prevent the lambda layer from calling the KMS service too often

## Steps to Reproduce

Using the layer as written with an unencrypted SUMO_HTTP_ENDPOINT env var in the lambda definition

## Expected Behavior

Provide a KMS encrypted string of the SUMO_HTTP_ENDPOINT and a KMS_KEY_ID and the layer will decrypt the endpoint value as needed

## Relevant Logs / Console output

[NOTE]: # ( Please provide error logs if possible. )

## Your Environment

AWS Lambda functions written in javascript and python

## Additional context

The same feature could be provided for getting the secret from SSM, but SSM does have lower limits and higher cost

**Comment by himanshu219** [comment]
Merged
