### ISSUE TITLE
Auto update layer verion

### ISSUE THREAD

**Issue by maksymsereda** [SumoLogic/sumologic-lambda-extensions#22]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
Hi,
Is there a way how to automatically update the layer version in terraform? We have a value in our terraform code as shown below, but all the time the new version release we have to update it manually (f.e. from 6 to 7)
arn:aws:lambda:<AWS_REGION>:956882708938:layer:sumologic-extension-amd64:7

Probably the tag latest could be added?

## Expected Behavior

[NOTE]: # ( Tell us about the behavior you expect. )
Latest tag

## Relevant Logs / Console output

[NOTE]: # ( Please provide error logs if possible. )
As for now the logs with the latest tag are the following
`Error: updating Lambda Function (dominos-jpn-dev-auth-lambda) configuration: operation error Lambda: UpdateFunctionConfiguration, https response error StatusCode: 400, RequestID: b8a059f9-22c0-48ff-95de-a5c2620f8cb7, api error ValidationException: 1 validation error detected: Value '[arn:aws:lambda:ap-northeast-1:956882708938:layer:sumologic-extension-amd64:latest]' at 'layers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 140, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: (arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+), Member must not be null]
with module.auth.module.lambda_function_auth.aws_lambda_function.this[0]`

**Comment by himanshu219** [comment]
there is unfortunately no way to tag the layer but you can use custom resource 
https://stackoverflow.com/questions/62979100/configure-aws-lambda-function-to-use-latest-version-of-a-layer
