### ISSUE TITLE
SUMO_ENHANCE_JSON_LOGS has opposite functionality

### ISSUE THREAD

**Issue by lopezm1** [SumoLogic/sumologic-lambda-extensions#23]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )

The environment variable `SUMO_ENHANCE_JSON_LOGS=false` is doing the opposite of it's documented usage. 

According to the release page: 
```
Introduced a new environment variable SUMO_ENHANCE_JSON_LOGS which by default is set to true. If the feature switch is set to false then the message sent to SumoLogic will not contain any addition metadata only the actual log message.
```

## Steps to Reproduce

[NOTE]: # ( Please give detailed steps to reproduce the issue. )
Set your `environment` variables for lambda functions:
```
  REGION: ${self:provider.region}
  SUMO_ENHANCE_JSON_LOGS: true
  SUMO_HTTP_ENDPOINT: ${self:custom.sumo-http-endpoint}
  SUMO_LOG_TYPES: function
 ```
 
 Add the following layer to your lambda:
 ```
 arn:aws:lambda:${self:provider.region}:956882708938:layer:sumologic-extension-amd64:7
 ```
 

## Expected Behavior

[NOTE]: # ( Tell us about the behavior you expect. )

I would expect the logs to look like this: 
```
{"message":{"asctime":"2023-07-18 23:18:13,355","funcName":"send","levelname":"INFO","message":"GET / 200","module":"http"}}
```

No extra metadata from the lambda, only a log message.

## Relevant Logs / Console output

[NOTE]: # ( Please provide error logs if possible. )

Instead, the logs contain anything but the `message` and they look like this: 
```
{"IsColdStart":false,"LayerVersion":"sumologic-extension-prod:7","logGroup":"/aws/lambda/tcr-service-fastapi-lambda-dev-apiPublic","logStream":"2023/07/18/[$LATEST]sumologic-extension","time":"2023-07-18T23:18:13.356Z","type":"function"}
```

## Your Environment

[TIP]:  # ( Include details about your AWS or local environment. )

Layer version: arn:aws:lambda:${self:provider.region}:956882708938:layer:sumologic-extension-amd64:7
RunTime: Python3.9
Timeout and other Environment Variables
```
  REGION: ${self:provider.region}
  SUMO_ENHANCE_JSON_LOGS: true
  SUMO_HTTP_ENDPOINT: ${self:custom.sumo-http-endpoint}
  SUMO_LOG_TYPES: function
 ```

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by lacer93** [comment]
Yes, unfortunately this is correct. I added that feature switch but with my limited Go knowledge it seems like I messed up. Sadly I haven't got around to fixing it ever since.

**Comment by lopezm1** [comment]
@lacer93 appreciate the quick response! Any chance we can work with you to prioritize this in the near future? We would love to have this feature for slimmer logs.

**Comment by lacer93** [comment]
@lopezm1 I am not associated with SumoLogic, I implemented the changes because I was interested in something like this myself. I would still like to have it, but I haven't had any free capacity to get around to fixing it and I won't have any in the near future sadly.
