### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by HaroonSaid** [SumoLogic/sumologic-lambda-extensions#5]
Are there any example of 
* how to use the extension for Python and C#
* how do i pass API token

**Comment by SumoSourabh** [comment]
1. Extension is an executable binary (does not depend on lambda Runtime) that can be added as layer to your lambda. So, you can add it as layer to your lambda.
2. You do not need an API token. To send Logs to Sumo logic, provide the HTTP URL of the source.

**Comment by SumoSourabh** [comment]
Details - https://help.sumologic.com/03Send-Data/Collect-from-Other-Data-Sources/Collect_AWS_Lambda_Logs_using_an_Extension

**Comment by SumoSourabh** [comment]
Answered
