### ISSUE TITLE
Try parsing message as JSON text

### ISSUE THREAD

**Issue by ykitamura-mdsol** [SumoLogic/sumologic-lambda-extensions#6]
## Description

When a JSON string is logged, it shows up as a JSON string in SumoLogic.

## Steps to Reproduce

```python
def lambda_handler(event, context):
    print(json.dumps({"hello": "lambda"}))
```
⬇️ 

<img width="377" alt="Screen Shot 2021-02-12 at 6 31 17 PM" src="https://user-images.githubusercontent.com/16286071/107834367-f2f0f680-6d63-11eb-9803-4cc282fe05dd.png">

## Expected Behavior

Ideally, I want to have it as a JSON object:

<img width="406" alt="Screen Shot 2021-02-12 at 6 44 22 PM" src="https://user-images.githubusercontent.com/16286071/107834409-14ea7900-6d64-11eb-9026-5345a155b272.png">

## Relevant Logs / Console output

N/A

## Your Environment

* Layer version: 1
* RunTime: Python 3.8
* Environment Variables
  * SUMO_HTTP_ENDPOINT=my endpoint
  * SUMO_LOG_TYPES=function

## Additional context

Here is my trial code:
https://github.com/SumoLogic/sumologic-lambda-extensions/compare/main...ykitamura-mdsol:feature/try_parsing_message?expand=1

**Comment by SumoSourabh** [comment]
Hi,

We tried the same code. Here is the way you can read JSON in Sumo Logic.

Below is the code.

<img width="340" alt="Screenshot 2021-02-15 at 11 52 37 AM" src="https://user-images.githubusercontent.com/45626610/107912460-8a349480-6f84-11eb-9365-708dba638049.png">

Below is the response received in Sumo Logic

<img width="476" alt="Screenshot 2021-02-15 at 11 54 13 AM" src="https://user-images.githubusercontent.com/45626610/107912525-a5070900-6f84-11eb-85e3-07250aba1b65.png">

Below is the query used to parse message

<img width="325" alt="Screenshot 2021-02-15 at 11 52 14 AM" src="https://user-images.githubusercontent.com/45626610/107912544-b05a3480-6f84-11eb-8cc8-dd7c12cf8034.png">

Below is the output

<img width="1003" alt="Screenshot 2021-02-15 at 11 55 50 AM" src="https://user-images.githubusercontent.com/45626610/107912641-de3f7900-6f84-11eb-8014-ba139a361a3d.png">

Let us know if it helps.

**Comment by ykitamura-mdsol** [comment]
thanks for the tip! will try it out.
