### ISSUE TITLE
Fields configuration question

### ISSUE THREAD

**Issue by dsantimore-linus** [SumoLogic/sumologic-lambda-extensions#9]
Simple question after reading the docs here and at sumo:

I see that you can configure the sourceCategory value -- can you also configure the name-value fields?

**Comment by himanshu219** [comment]
do you mean source name?

**Comment by dsantimore-linus** [comment]
Hi @himanshu219 , I'm referring to the metadata type fields that are supplied with the http source as headers. I'm wondering if we are able to do that here (it's actually really nice for CI/CD setups), or if we'd have to use a Field Extraction Rule.

**Comment by himanshu219** [comment]
Support of metadata fields (X-SUMO-Fields) in http headers  is currently not supported.
